### ISSUE TITLE
Loading theme resource error due to cross-origin policy

### ISSUE THREAD

**Issue by neolee** [uwu/monaco-react#2]
I'm using your Monaco Editor plugin for solidjs, worked perfectly until recently. Seems broken on loading theme resource with error message in browser console:

```
[Error] Failed to load resource: Cross-origin redirection to https://esm.sh/monaco-themes@0.4.2/themes/Dracula.json denied by Cross-Origin Resource Sharing policy: Origin [my site host] is not allowed by Access-Control-Allow-Origin. Status code: 301 (Dracula.json, line 0)
```

Seems esm.sh has changed their cross-origin policy?

**Comment by yellowsink** [comment]
Looks fine to me?
![image](https://user-images.githubusercontent.com/19270622/231750692-e18006a1-f305-4394-aabc-262183b42e19.png)

What's your `Content-Security-Policy`?

If it is a problem, I can add the ability to pass the theme object directly in

**Comment by maisymoe** [comment]
I also started encountering this issue on https://devsocket.beefers.dev/

**Comment by yellowsink** [comment]
I've had issues in the past, I suspect it's the redirect server 

I can look into switching to unpkg/jsdelivr/esm.run/etc.

**Comment by neolee** [comment]
> Looks fine to me? ![image](https://user-images.githubusercontent.com/19270622/231750692-e18006a1-f305-4394-aabc-262183b42e19.png)
> 
> What's your `Content-Security-Policy`?

`Referrer Policy: strict-origin-when-cross-origin`

Never changed related config though. 

> If it is a problem, I can add the ability to pass the theme object directly in

Might be a good idea :)

**Comment by yellowsink** [comment]
I know this *isn't a solution*, but to see if its a viable fix to change the CDN / allow choosing a CDN, can you find `node_modules/@uwu/monaco-solid/dist/monaco.js`, and try swapping
```js
const u = `https://cdn.esm.sh/monaco-themes@0.4.2/themes/${t}.json`;
```
for
```js
const u = `https://cdn.jsdelivr.net/npm/monaco-themes@0.4.2/themes/${t}.json`;
```
and see if that fixes it?

If so, I intend to make that change properly, as I have had CSP/CORS issue with esm.sh before, and jsdelivr should handle it fine (?)

If not, then yeah I'll implement passing in the theme as just a JS object, so you can bundle it.

**Comment by neolee** [comment]
@yellowsink I'm sorry but when I tried the CDN swapping as you said, the issue seems gone. Both CDN(esm&jsdelivr) work well now. Have no idea what's going on. But it's good that esm works as before and you do not need to fix anything. 

Thanks for your time anyway.

**Comment by yellowsink** [comment]
Well if it's working now that's all good then, if it happens again feel free to reopen.

Happy to help :)
