### ISSUE TITLE
monaco-svelte, get an instance

### ISSUE THREAD

**Issue by laldana73** [uwu/monaco-react#3]
Hello.
Please, how can i get an instance of the component in order to update some properties, as fontSize or others?

**Comment by yellowsink** [comment]
At the moment there isn't a way to get an instance of the monaco editor, but you should be able to pass font size in via `otherCfg`, I believe.

**Comment by yellowsink** [comment]
My bad, otherCfg isn't currently reactive, so this doesn't work yet.

**Comment by yellowsink** [comment]
This is implemented as of 1846bf4, it will be released once there are react & vue implementations of it too.

**Comment by yellowsink** [comment]
done. @uwu/monaco-svelte@^1.2.0
